package hello.bean;

public class CollectionBuilder {
    static long i = 0;
    public static boolean withId = false;
    public static Collection getCollection() {
        Collection c = new Collection();
        c.setId(next(withId));
        c.addSerie(new Serie( "Arawn")
                .addPossede( "1", "Bran le Maudit", "https://www.bedetheque.com/media/Couvertures/Arawn1_26012008_153221.jpg")
                .addPossede( "2", "Les liens du sang", "https://www.bedetheque.com/media/Couvertures/Arawn2_22012009_150322.jpg")
                .addPossede( "3", "La Bataille de Cad Goddun", "http://www.bedetheque.com/media/Couvertures/Couv_104011.jpg")
                .addPossede( "4", "Le chaudron de sang", "http://www.bedetheque.com/media/Couvertures/Couv_133430.jpg")
                .addPossede( "5", "Résurrection", "http://www.bedetheque.com/media/Couvertures/Couv_173868.jpg")
                .addPossede( "6", "La terre brulée", "http://www.bedetheque.com/media/Couvertures/Couv_217875.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Arawn1_26012008_153221.jpg")
                .withEditeur("Soleil Celtic")
                .withFini(false));


        c.addSerie(new Serie( "Mjollnir")
                .addPossede( "1", "Le Marteau et l'Enclume", "http://www.bedetheque.com/media/Couvertures/Couv_179118.jpg")
                .addPossede( "2", "Ragnarok", "http://www.bedetheque.com/media/Couvertures/Couv_192958.jpg")
                .addPossede("3","un monde sans Dieux","http://www.bedetheque.com/media/Couvertures/Couv_282993.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_179118.jpg")
                .withEditeur("Soleil Celtic")
                .withFini(true));

        c.addSerie(new Serie( "Okko")
                .addPossede( "1", "Le cycle de l'eau - I", "http://www.bedetheque.com/media/Couvertures/Couv_41693.jpg")
                .addPossede( "2", "Le cycle de l'eau - II", "http://www.bedetheque.com/media/Couvertures/Couv_53164.jpg")
                .addPossede( "3", "Le cycle de la terre - I", "http://www.bedetheque.com/media/Couvertures/Couv_60045.jpg")
                .addPossede( "4", "Le cycle de la terre - II", "http://www.bedetheque.com/media/Couvertures/Couv_71412.jpg")
                .addPossede( "5", "Le cycle de l'air - I", "http://www.bedetheque.com/media/Couvertures/Couv_85305.jpg")
                .addPossede( "6", "Le cycle de l'air - II", "http://www.bedetheque.com/media/Couvertures/Couv_108701.jpg")
                .addPossede( "7", "Le cycle du feu - I", "http://www.bedetheque.com/media/Couvertures/Couv_138187.jpg")
                .addPossede( "8", "Le cycle du feu - II", "http://www.bedetheque.com/media/Couvertures/Couv_176657.jpg")
                .addPossede( "9", "Le cycle du vide - I", "http://www.bedetheque.com/media/Couvertures/Couv_215611.jpg")
                .addPossede( "10", "Le cycle du vide - II", "http://www.bedetheque.com/media/Couvertures/Couv_258069.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_41693.jpg")
                .withEditeur("Delcourt")
                .withFini(false));

        c.addSerie(new Serie( "La licorne")
                .addPossede( "1", "Le Dernier Temple d'Asclépios", "http://www.bedetheque.com/media/Couvertures/Couv_58319.jpg")
                .addPossede( "2", "Ad Naturam", "http://www.bedetheque.com/media/Couvertures/Couv_71167.jpg")
                .addPossede( "3", "Les Eaux noires de Venise", "http://www.bedetheque.com/media/Couvertures/Couv_96622.jpg")
                .addPossede( "4", "Le jour du Baptême", "http://www.bedetheque.com/media/Couvertures/Couv_154596.jpg")
                .addManquante( "HS1", "Le Grimoire de La Licorne 12/2010", "http://www.bedetheque.com/media/Couvertures/Couv_119410.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_58319.jpg")
                .withEditeur("Delcourt")
                .withFini(false));

        c.addSerie(new Serie ("Reign")
                .addPossede("1","Day One","https://www.bedetheque.com/media/Couvertures/reign01_83110.jpg")
                .addPossede("2","Seconde chance","https://www.bedetheque.com/media/Couvertures/Couv_96355.jpg")
                .addPossede("3","Troisième escadre","https://www.bedetheque.com/media/Couvertures/Couv_111986.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/reign01_83110.jpg")
                .withEditeur("Soleil Productions")
                .withFini(false)
        );

        c.addSerie(new Serie( "Samurai")
                .addPossede( "1", "Le Coeur du Prophète", "http://www.bedetheque.com/media/Couvertures/samurai01.jpg")
                .addPossede( "2", "Les Sept Sources d'Akanobu", "http://www.bedetheque.com/media/Couvertures/samurai02.jpg")
                .addPossede( "3", "Le Treizième Prophète", "http://www.bedetheque.com/media/Couvertures/samurai03.jpg")
                .addPossede( "4", "Le rituel de Morinaga", "http://www.bedetheque.com/media/Couvertures/Samurai4_21102008_233157.jpg")
                .addPossede( "5", "L'Île sans nom", "http://www.bedetheque.com/media/Couvertures/Couv_103993.jpg")
                .addPossede( "6", "Shobei", "http://www.bedetheque.com/media/Couvertures/Couv_118958.jpg")
                .addPossede( "7", "Frères d'armes", "http://www.bedetheque.com/media/Couvertures/Couv_144397.jpg")
                .addPossede( "8", "Frères de sang", "http://www.bedetheque.com/media/Couvertures/Couv_174222.jpg")
                .addPossede( "9", "Ogomo", "http://www.bedetheque.com/media/Couvertures/Couv_217764.jpg")
                .addPossede( "10", "Ririko", "http://www.bedetheque.com/media/Couvertures/Couv_258014.jpg")
                .addPossede( "11", "Le sabre et le lotus", "https://www.bedetheque.com/media/Couvertures/Couv_305167.jpg")
                .addPossede("12","L'Œil du dragon","https://www.bedetheque.com/media/Couvertures/Couv_332537.jpg")
                .addManquante("13","Piment rouge et alcool blanc","https://www.bedetheque.com/media/Couvertures/Couv_363862.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/samurai01.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "Chroniques de la guerre des Fees")
                .addPossede( "1", "Dans la gueule du loup", "http://www.bedetheque.com/media/Couvertures/Couv_135417.jpg")
                .addPossede( "2", "Aedlyn", "http://www.bedetheque.com/media/Couvertures/Couv_162154.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_135417.jpg")
                .withEditeur("Soleil Celtic")
                .withFini(true));

        c.addSerie(new Serie( "Samurai Légendes")
                .addPossede( "1", "Furiko", "http://www.bedetheque.com/media/Couvertures/Couv_176099.jpg")
                .addPossede( "2", "L'échange", "http://www.bedetheque.com/media/Couvertures/Couv_201038.jpg")
                .addPossede( "3", "L'aube Rouge", "http://www.bedetheque.com/media/Couvertures/Couv_227960.jpg")
                .addPossede("4"," Vents de colère","http://www.bedetheque.com/media/Couvertures/Couv_282951.jpg")
                .addPossede("5","Trompeuses apparences","https://www.bedetheque.com/media/Couvertures/Couv_346499.jpg")
                .addManquante("6","Reiko","https://www.bedetheque.com/media/Couvertures/Couv_375014.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_201038.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Samurai Origines ")
                .addManquante( "1", "Takeo", "https://www.bedetheque.com/media/Couvertures/Couv_311651.jpg")
                .addManquante( "2", "Le Maître des encens", "https://www.bedetheque.com/media/Couvertures/Couv_361250.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_311651.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Les rois forgerons")
                .addPossede( "1", "Le Sceau de Karzac Um Rork", "http://www.bedetheque.com/media/Couvertures/Couv_136137.jpg")
                .addPossede( "2", "Le Petit Père des Elfes", "http://www.bedetheque.com/media/Couvertures/Couv_185526.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_136137.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Nuit Safran")
                .addPossede( "1", "Albumen l'éthéré", "http://www.bedetheque.com/media/Couvertures/Couv_107222.jpg")
                .addPossede( "2", "La vengeance d'Albumen", "http://www.bedetheque.com/media/Couvertures/Couv_151769.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_107222.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Konungar")
                .addPossede( "1", "Invasions", "http://www.bedetheque.com/media/Couvertures/Couv_126735.jpg")
                .addPossede( "2", "Les guerriers du neant", "http://www.bedetheque.com/media/Couvertures/Couv_167459.jpg")
                .addPossede( "3", "Le châtiment", "http://www.bedetheque.com/media/Couvertures/Couv_195618.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_126735.jpg")
                .withEditeur("Glenat")
                .withFini(true));

        c.addSerie(new Serie( "Les arcanes d'Alya")
                .addPossede( "1", "La chasseresse écarlate", "http://www.bedetheque.com/media/Couvertures/ArcanesDalya01_66103.jpg")
                .addPossede( "2", "Ames soeurs", "http://www.bedetheque.com/media/Couvertures/ArcanesDalyaLes2_26012008_162242.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/ArcanesDalya01_66103.jpg")
                .withFini(true)
                .withEditeur("Soleil"));

        c.addSerie(new Serie( "Le chant des Stryges")
                .addPossede( "1", "Ombres", "https://www.bedetheque.com/media/Couvertures/Couv_113601.jpg")
                .addManquante( "2", "Pièges", "https://www.bedetheque.com/media/Couvertures/Couv_6236.jpg")
                .addManquante( "3", "Emprises", "https://www.bedetheque.com/media/Couvertures/Couv_6237.jpg")
                .addManquante( "4", "Expériences", "https://www.bedetheque.com/media/Couvertures/Couv_6238.jpg")
                .addManquante( "5", "Vestiges", "https://www.bedetheque.com/media/Couvertures/Couv_6239.jpg")
                .addManquante( "6", "Existences", "https://www.bedetheque.com/media/Couvertures/Couv_12354.jpg")
                .addManquante( "7", "Rencontres", "https://www.bedetheque.com/media/Couvertures/Couv_26232.jpg")
                .addManquante( "8", "Défis", "https://www.bedetheque.com/media/Couvertures/Couv_36505.jpg")
                .addManquante( "9", "Révélations", "https://www.bedetheque.com/media/Couvertures/Couv_49296.jpg")
                .addManquante( "10", "Manipulations", "https://www.bedetheque.com/media/Couvertures/Couv_57960.jpg")
                .addManquante( "11", "Cellules", "https://www.bedetheque.com/media/Couvertures/Couv_66440.jpg")
                .addManquante( "12", "Chutes", "https://www.bedetheque.com/media/Couvertures/Couv_79475.jpg")
                .addManquante( "13", "Pouvoirs", "https://www.bedetheque.com/media/Couvertures/Couv_113601.jpg")
                .addManquante( "14", "Enlèvements", "https://www.bedetheque.com/media/Couvertures/Couv_141742.jpg")
                .addManquante( "15", "Hybrides", "https://www.bedetheque.com/media/Couvertures/Couv_185982.jpg")
                .addManquante( "16", "Exécutions", "https://www.bedetheque.com/media/Couvertures/Couv_227333.jpg")
                .addManquante("17","Réalités","https://www.bedetheque.com/media/Couvertures/Couv_273731.jpg")
                .addManquante("18","Mythes","https://www.bedetheque.com/media/Couvertures/Couv_336509.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_113601.jpg")
                .withEditeur("Delcourt")
                .withFini(false));

        c.addSerie(new Serie( "La geste des chevaliers Dragon")
                .addPossede( "1", "Jaina", "http://www.bedetheque.com/media/Couvertures/gestechevaliersdragons01.jpg")
                .addPossede( "2", "Akanah", "http://www.bedetheque.com/media/Couvertures/Couv_31479.jpg")
                .addPossede( "3", "Le pays de non-vie", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliersdragons03.jpg")
                .addPossede( "4", "Brisken", "http://www.bedetheque.com/media/Couvertures/gestedeschevalierdragon04.jpg")
                .addPossede( "5", "Les Jardins du Palais", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliersdragons05.JPG")
                .addPossede( "6", "Par-delà les montagnes", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliersdragons06.jpg")
                .addPossede( "7", "Revoir le soleil", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliersdragonscouv07_73906.jpg")
                .addPossede( "8", "Le chœur des ténèbres", "http://www.bedetheque.com/media/Couvertures/GesteDesChevaliersDragons08_87981.jpg")
                .addPossede( "9", "Aveugles", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliers09_100269.jpg")
                .addPossede( "10", "Vers la lumière", "http://www.bedetheque.com/media/Couvertures/gestedeschevaliersdragons10_108922.jpg")
                .addPossede( "11", "Toutes les mille et une lunes", "http://www.bedetheque.com/media/Couvertures/Couv_118387.jpg")
                .addPossede( "12", "Ellys", "http://www.bedetheque.com/media/Couvertures/Couv_133420.jpg")
                .addPossede( "13", "Salmyre", "http://www.bedetheque.com/media/Couvertures/Couv_144394.jpg")
                .addPossede( "14", "La Première", "http://www.bedetheque.com/media/Couvertures/Couv_165829.jpg")
                .addPossede( "15", "L'Ennemi", "http://www.bedetheque.com/media/Couvertures/Couv_176575.jpg")
                .addPossede( "16", "La Déesse", "http://www.bedetheque.com/media/Couvertures/Couv_190907.jpg")
                .addPossede( "17", "Amarelle - La Guerre des Sardes - I", "http://www.bedetheque.com/media/Couvertures/Couv_200889.jpg")
                .addPossede( "18", "Amarelle - La Guerre des Sardes - II", "http://www.bedetheque.com/media/Couvertures/Couv_217069.jpg")
                .addPossede( "19", "L'Antidote", "http://www.bedetheque.com/media/Couvertures/Couv_227228.jpg")
                .addPossede( "20", "Naissance d'un empire", "http://www.bedetheque.com/media/Couvertures/Couv_250497.jpg")
                .addPossede( "21", "La Faucheuse d'Ishtar", "http://www.bedetheque.com/media/Couvertures/Couv_260161.jpg")
                .addPossede("22","La porte du Nord","http://www.bedetheque.com/media/Couvertures/Couv_283297.jpg")
                .addPossede("23","La mer close","http://www.bedetheque.com/media/Couvertures/Couv_291414.jpg")
                .addPossede("24","Les Nuits d'Haxinandrie","https://www.bedetheque.com/media/Couvertures/Couv_305173.jpg")
                .addPossede("25","La guerre des ombres","https://www.bedetheque.com/media/Couvertures/Couv_315469.jpg")
                .addPossede("26","Nous ne nous reverrons jamais","https://www.bedetheque.com/media/Couvertures/Couv_336110.jpg")
                .addPossede("27","Le Draconomicon","https://www.bedetheque.com/media/Couvertures/Couv_350715.jpg" )
                .addManquante("28","Contrebandes","https://www.bedetheque.com/media/Couvertures/Couv_368426.jpg")
                .addManquante("29","Les Sœurs de la Vengeance","https://www.bedetheque.com/media/Couvertures/Couv_378803.jpg")
                .addManquante( "HS1", "Les contrees du levant", "http://www.bedetheque.com/media/Couvertures/Couv_118631.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/gestechevaliersdragons01.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "Marie des dragons")
                .addPossede( "1", "Armance", "http://www.bedetheque.com/media/Couvertures/Couv_99004.jpg")
                .addPossede( "2", "Vengeances", "http://www.bedetheque.com/media/Couvertures/Couv_110858.jpg")
                .addPossede( "3", "Amaury", "http://www.bedetheque.com/media/Couvertures/Couv_118093.jpg")
                .addPossede( "4", "William", "http://www.bedetheque.com/media/Couvertures/Couv_143458.jpg")
                .addPossede( "5", "Les quatres", "http://www.bedetheque.com/media/Couvertures/Couv_199252.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_99004.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Beast")
                .addPossede( "1", "Yunze, le dieu gardien", "http://www.bedetheque.com/media/Couvertures/Beast1_20062008_225806.jpg")
                .addPossede( "2", "Amrath, la reine sauvage", "http://www.bedetheque.com/media/Couvertures/Beast2_02062009_002319.jpg")
                .addPossede( "3", "Tône-thet, le passeur d'âmes", "http://www.bedetheque.com/media/Couvertures/107550_c.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/107550_c.jpg")
                .withEditeur("Le Lombard")
                .withFini(true));

        c.addSerie(new Serie( "Lanfeust des etoiles")
                .addPossede( "1", "Un, deux... Troy", "http://www.bedetheque.com/media/Couvertures/Couv_7299.jpg")
                .addPossede( "2", "Les tours de Meirrion", "http://www.bedetheque.com/media/Couvertures/Couv_24871.jpg")
                .addPossede( "3", "Les sables d'Abraxar", "http://www.bedetheque.com/media/Couvertures/Couv_32527.jpg")
                .addPossede( "4", "Les buveurs de mondes", "http://www.bedetheque.com/media/Couvertures/Couv_41053.jpg")
                .addPossede( "5", "La chevauchée des bactéries", "http://www.bedetheque.com/media/Couvertures/Couv_52352.jpg")
                .addPossede( "6", "Le râle du flibustier", "http://www.bedetheque.com/media/Couvertures/Couv_59589.jpg")
                .addPossede( "7", "Le secret des Dolphantes", "http://www.bedetheque.com/media/Couvertures/Couv_69820.jpg")
                .addPossede( "8", "Le sang des comètes", "http://www.bedetheque.com/media/Couvertures/Couv_80608.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_7299.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Lanfeust de Troy Integrales")
                .addPossede( "1", "Volumes 1 2 3", "http://www.bedetheque.com/media/Couvertures/Couv_163937.jpg")
                .addPossede( "2", "Volumes 4 5 6", "http://www.bedetheque.com/media/Couvertures/Couv_172349.jpg")
                .addPossede( "3", "Volumes 7 8 encyclopedie", "http://www.bedetheque.com/media/Couvertures/Couv_177029.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_163937.jpg")
                .withEditeur("Soleil")
                .withFini(false));
        c.addSerie(new Serie( "Lanfeust de Troy")
                .addManquante("1","1", "")
                .addManquante("2","2", "")
                .addManquante("3","3", "")
                .addManquante("4","4", "")
                .addManquante("5","5", "")
                .addManquante("6","6", "")
                .addManquante("7","7", "")
                .addPossede("8","La bête fabuleuse", "http://www.bedetheque.com/media/Couvertures/Couv_2107.jpg")
                .withEditeur("Soleil")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_2107.jpg")
        );

        c.addSerie(new Serie( "Les chroniques de la lune noire")
                .addPossede( "1", "Le Signe des Ténèbres", "http://www.bedetheque.com/media/Couvertures/Couv_136.jpg")
                .addPossede( "2", "Le vent des Dragons", "http://www.bedetheque.com/media/Couvertures/Couv_137.jpg")
                .addPossede( "3", "La Marque des Démons", "http://www.bedetheque.com/media/Couvertures/Couv_138.jpg")
                .addManquante("3 TRANCHE ROUGE", "La Marque des Démons", "http://www.bedetheque.com/media/Couvertures/Couv_138.jpg")
                .addPossede( "4", "Quand sifflent les Serpents", "http://www.bedetheque.com/media/Couvertures/Couv_139.jpg")
                .addPossede( "5", "La danse écarlate", "http://www.bedetheque.com/media/Couvertures/Couv_585.jpg")
                .addPossede( "6", "La Couronne des Ombres", "http://www.bedetheque.com/media/Couvertures/Couv_684.jpg")
                .addPossede( "7", "De Vents, de Jade et de Jais", "http://www.bedetheque.com/media/Couvertures/Couv_955.jpg")
                .addPossede( "8", "Le Glaive de justice", "http://www.bedetheque.com/media/Couvertures/Couv_1512.jpg")
                .addPossede( "9", "Les Chants de la négation", "http://www.bedetheque.com/media/Couvertures/chroniquesdelalunenoire09.jpg")
                .addPossede( "10", "L'Aigle foudroyé", "http://www.bedetheque.com/media/Couvertures/chroniquedelalunenoire10_13092002.jpg")
                .addPossede( "11", "Ave Tenebrae", "http://www.bedetheque.com/media/Couvertures/Couv_29789.jpg")
                .addPossede( "12", "La Porte des Enfers", "http://www.bedetheque.com/media/Couvertures/ChroniquesDeLaLuneNoire12_08062005.jpg")
                .addPossede( "13", "La Prophétie ", "http://www.bedetheque.com/media/Couvertures/chroniquesdelalunenoire13couv.jpg")
                .addPossede( "14", "La Fin des Temps", "http://www.bedetheque.com/media/Couvertures/ChroniquesDeLaLuneNoire14_25112008_200848.jpg")
                .addPossede( "15", "Terra Secunda - I", "http://www.bedetheque.com/media/Couvertures/Couv_176989.jpg")
                .addPossede( "16", "Terra Secunda - II", "http://www.bedetheque.com/media/Couvertures/Couv_225498.jpg")
                .addPossede("17","Guerres ophidiennes","http://www.bedetheque.com/media/Couvertures/Couv_258046.jpg")
                .addPossede("18","Le trône d'Opale","https://www.bedetheque.com/media/Couvertures/Couv_302798.jpg")
                .addPossede("19","Une semaine ordinaire", "https://www.bedetheque.com/media/Couvertures/Couv_344640.jpg")
                .addManquante("20","Une porte sur l'Enfer","https://www.bedetheque.com/media/Couvertures/Couv_378961.jpg")
                .addPossede( "HS1", "L'empire de la negation", "http://www.bedetheque.com/media/Couvertures/Couv_201795.jpg")
                .addPossede("0","En un jeu cruel","http://www.bedetheque.com/media/Couvertures/Couv_139500.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_955.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "Les arcanes de la lune noire")
                .addPossede( "1", "Ghorghor Bey", "http://www.bedetheque.com/media/Couvertures/arcanesdelalunenoire01.jpg")
                .addPossede( "2", "Pile-ou-Face", "http://www.bedetheque.com/media/Couvertures/froid.jpg")
                .addPossede( "3", "Parsifal", "http://www.bedetheque.com/media/Couvertures/116234_c.jpg")
                .addPossede( "4", "Greldinard - Première époque", "https://www.bedetheque.com/media/Couvertures/Couv_314513.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/froid.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "XIII")
                .addPossede( "1", "Le jour du soleil noir", "http://www.bedetheque.com/media/Couvertures/Couv_764.jpg")
                .addPossede( "2", "Là où va l'indien... ", "http://www.bedetheque.com/media/Couvertures/Couv_480.jpg")
                .addPossede( "3", "Toutes les larmes de l'enfer", "http://www.bedetheque.com/media/Couvertures/Couv_481.jpg")
                .addPossede( "4", "SPADS", "http://www.bedetheque.com/media/Couvertures/Couv_482.jpg")
                .addPossede( "5", "Rouge total", "http://www.bedetheque.com/media/Couvertures/Couv_483.jpg")
                .addPossede( "6", "Le dossier Jason Fly", "http://www.bedetheque.com/media/Couvertures/Couv_484.jpg")
                .addPossede( "7", "La nuit du 3 août", "http://www.bedetheque.com/media/Couvertures/Couv_485.jpg")
                .addPossede( "8", "Treize contre un", "http://www.bedetheque.com/media/Couvertures/Couv_486.jpg")
                .addPossede( "9", "Pour Maria", "http://www.bedetheque.com/media/Couvertures/Couv_487.jpg")
                .addPossede( "10", "El cascador", "http://www.bedetheque.com/media/Couvertures/Couv_508.jpg")
                .addPossede( "11", "Trois montres d'argent", "http://www.bedetheque.com/media/Couvertures/Couv_683.jpg")
                .addPossede( "12", "Le jugement", "http://www.bedetheque.com/media/Couvertures/Couv_1073.jpg")
                .addManquante("13","l'enquete","http://www.bedetheque.com/media/Couvertures/Couv_1541.jpg")
                .addManquante("13 bis","L'enquête - Deuxième partie","https://www.bedetheque.com/media/Couvertures/Couv_350218.jpg")
                .addPossede( "14", "Secret défense", "http://www.bedetheque.com/media/Couvertures/Couv_2073.jpg")
                .addPossede( "15", " Lachez les chiens !", "http://www.bedetheque.com/media/Couvertures/Couv_11781.jpg")
                .addPossede( "16", "Opération Montecristo", "http://www.bedetheque.com/media/Couvertures/Couv_33245.jpg")
                .addPossede( "17", "L'or de Maximilien", "http://www.bedetheque.com/media/Couvertures/Couv_49961.jpg")
                .addPossede( "18", "La version Irlandaise", "http://www.bedetheque.com/media/Couvertures/Couv_68485.jpg")
                .addPossede( "19", "Le dernier round", "http://www.bedetheque.com/media/Couvertures/xiii19couv.jpg")
                .addPossede( "20", " Le jour du Mayflower", "http://www.bedetheque.com/media/Couvertures/Couv_141327.jpg")
                .addPossede( "21", "L'appât", "http://www.bedetheque.com/media/Couvertures/Couv_170163.jpg")
                .addPossede( "22", "Retour à Greenfalls", "http://www.bedetheque.com/media/Couvertures/Couv_195999.jpg")
                .addPossede( "23", "Le Message du martyr", "http://www.bedetheque.com/media/Couvertures/Couv_225425.jpg")
                .addPossede("24","L'Héritage de Jason Mac Lane","http://www.bedetheque.com/media/Couvertures/Couv_277935.jpg")
                .addManquante("25","The XIII history","https://www.bedetheque.com/media/Couvertures/Couv_373052.jpg")
                .addManquante("26","2132 mètres","https://www.bedetheque.com/media/Couvertures/Couv_377348.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_177856.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "Thorgal")
                .addPossede( "1", "La magicienne trahie", "http://www.bedetheque.com/media/Couvertures/Couv_398.jpg")
                .addPossede( "2", "L'île des mers gelées", "http://www.bedetheque.com/media/Couvertures/thorgal02.jpg")
                .addPossede( "3", "Les trois vieillards du pays d'Aran", "http://www.bedetheque.com/media/Couvertures/thorgal03.jpg")
                .addPossede( "4", "La galère noire", "http://www.bedetheque.com/media/Couvertures/Couv_401.jpg")
                .addPossede( "5", "Au-delà des ombres", "http://www.bedetheque.com/media/Couvertures/Couv_402.jpg")
                .addPossede( "6", "La chute de Brek Zarith", "http://www.bedetheque.com/media/Couvertures/Couv_403.jpg")
                .addPossede( "7", "L'enfant des étoiles", "http://www.bedetheque.com/media/Couvertures/Couv_404.jpg")
                .addPossede( "8", "Alinoë", "http://www.bedetheque.com/media/Couvertures/Couv_405.jpg")
                .addPossede( "9", "Les archers", "http://www.bedetheque.com/media/Couvertures/Couv_406.jpg")
                .addPossede( "10", "Le pays Qâ", "http://www.bedetheque.com/media/Couvertures/Couv_407.jpg")
                .addPossede( "11", "Les yeux de Tanatloc", "http://www.bedetheque.com/media/Couvertures/Couv_408.jpg")
                .addPossede( "12", "La cité du dieu perdu", "http://www.bedetheque.com/media/Couvertures/Couv_409.jpg")
                .addPossede( "13", " Entre terre et lumière", "http://www.bedetheque.com/media/Couvertures/Couv_410.jpg")
                .addPossede( "14", "Aaricia", "http://www.bedetheque.com/media/Couvertures/Couv_411.jpg")
                .addPossede( "15", "Le maître des montagnes", "http://www.bedetheque.com/media/Couvertures/Couv_412.jpg")
                .addPossede( "16", "Louve", "http://www.bedetheque.com/media/Couvertures/Couv_413.jpg")
                .addManquante( "17", "La gardienne des clés", "http://www.bedetheque.com/media/Couvertures/Couv_414.jpg")
                .addManquante( "18", " L'épée-Soleil", "http://www.bedetheque.com/media/Couvertures/Couv_415.jpg")
                .addManquante( "19", "La forteresse invisible", "http://www.bedetheque.com/media/Couvertures/Couv_416.jpg")
                .addManquante( "20", "La marque des bannis", "http://www.bedetheque.com/media/Couvertures/Couv_668.jpg")
                .addManquante( "21", "La couronne d'Ogotaï", "http://www.bedetheque.com/media/Couvertures/Couv_810.jpg")
                .addPossede( "22", "Géants", "http://www.bedetheque.com/media/Couvertures/Couv_927.jpg")
                .addManquante( "23", "La cage", "http://www.bedetheque.com/media/Couvertures/Couv_1109.jpg")
                .addPossede( "24", "Arachnéa", "http://www.bedetheque.com/media/Couvertures/Couv_1588.jpg")
                .addManquante( "25", "Le Mal bleu", "http://www.bedetheque.com/media/Couvertures/Couv_1803.jpg")
                .addManquante( "26", "Le Royaume sous le Sable", "http://www.bedetheque.com/media/Couvertures/Couv_6894.jpg")
                .addPossede( "27", "Le Barbare", "http://www.bedetheque.com/media/Couvertures/Couv_19993.jpg")
                .addPossede( "28", "Kriss de Valnor", "http://www.bedetheque.com/media/Couvertures/Couv_39436.jpg")
                .addManquante( "29", "Le Sacrifice", "http://www.bedetheque.com/media/Couvertures/Couv_59361.jpg")
                .addManquante( "30", "Moi, Jolan", "http://www.bedetheque.com/media/Couvertures/Couv_67373.jpg")
                .addPossede( "31", "Le bouclier de Thor", "http://www.bedetheque.com/media/Couvertures/Couv_80551.jpg")
                .addManquante( "32", "La Bataille d'Asgard", "http://www.bedetheque.com/media/Couvertures/Couv_117408.jpg")
                .addPossede( "33", "Le Bateau-Sabre", "http://www.bedetheque.com/media/Couvertures/Couv_140423.jpg")
                .addManquante( "34", "Kah-Aniel", "http://www.bedetheque.com/media/Couvertures/Couv_199374.jpg")
                .addManquante( "35", "Le feu écarlate", "http://www.bedetheque.com/media/Couvertures/Couv_292474.jpg")
                .addManquante("36","Aniel","https://www.bedetheque.com/media/Couvertures/Couv_348589.jpg")
                .addManquante("37","L'Ermite de Skellingar","https://www.bedetheque.com/media/Couvertures/Couv_375436.jpg")
                .addManquante( "HS1", "Trois femmes pour un heros", "http://www.bedetheque.com/media/Couvertures/Couv_170514.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_398.jpg")
                .withEditeur("Le Lombard")
                .withFini(false));

        c.addSerie(new Serie( "Les complaintes des landes perdues cycle 1")
                .addPossede( "1", "Sioban", "http://www.bedetheque.com/media/Couvertures/Couv_143.jpg")
                .addPossede( "2", "Blackmore", "http://www.bedetheque.com/media/Couvertures/Couv_601.jpg")
                .addPossede( "3", "Dame Gerfaut", "http://www.bedetheque.com/media/Couvertures/Couv_943.jpg")
                .addPossede( "4", "Kyle of Klanach", "http://www.bedetheque.com/media/Couvertures/Couv_1394.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_21792.jpg")
                .withEditeur("Dargaud")
                .withFini(true));

        c.addSerie(new Serie( "Les complaintes des landes perdues cycle 2 : Les chevaliers du pardon")
                .addPossede( "1", "Moriganes", "http://www.bedetheque.com/media/Couvertures/Couv_40118.jpg")
                .addPossede( "2", "Le Guinea Lord", "http://www.bedetheque.com/media/Couvertures/Couv_79248.jpg")
                .addPossede( "3", "La Fée Sanctus", "http://www.bedetheque.com/media/Couvertures/Couv_164562.jpg")
                .addPossede( "4", "Sill Valt", "http://www.bedetheque.com/media/Couvertures/Couv_223389.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_40118.jpg")
                .withEditeur("Dargaud")
                .withFini(true));

        c.addSerie(new Serie( "Les complaintes des landes perdues cycle 3 : Les sorcières")
                .addPossede("5","Tête noire","http://www.bedetheque.com/media/Couvertures/Couv_253349.jpg")
                .addPossede("6","Inferno","https://www.bedetheque.com/media/Couvertures/Couv_353803.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_253349.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "Angor")
                .addPossede("INT","Angor","https://www.bedetheque.com/media/Couvertures/Couv_305128.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_305128.jpg")
                .withEditeur("Soleil Productions")
                .withFini(true));

        c.addSerie(new Serie( "Crepuscule des dieux")
                .addPossede( "0", "La Malédiction de l'Anneau", "http://www.bedetheque.com/media/Couvertures/CrepusculeDesDieuxLe0_24072009_052139.jpg")
                .addPossede( "1", "La Malédiction des Nibelungen", "http://www.bedetheque.com/media/Couvertures/CrepusculeDesDieuxLe1_22052007_62832.jpg")
                .addPossede( "2", "Siegfried", "http://www.bedetheque.com/media/Couvertures/CrepusculeDesDieuxLe2_20112007_205902.jpg")
                .addPossede( "3", "Fafner", "http://www.bedetheque.com/media/Couvertures/CrepusculeDesDieuxLe3_22012009_150728.jpg")
                .addPossede( "4", "Brunhilde", "http://www.bedetheque.com/media/Couvertures/Couv_108921.jpg")
                .addPossede( "5", "Kriemhilde", "http://www.bedetheque.com/media/Couvertures/Couv_118204.jpg")
                .addPossede( "6", "Ragnarök", "http://www.bedetheque.com/media/Couvertures/Couv_151181.jpg")
                .addPossede( "7", "Le Grand Hiver", "http://www.bedetheque.com/media/Couvertures/Couv_191291.jpg")
                .addPossede( "8", "Le Sang d'Odin", "http://www.bedetheque.com/media/Couvertures/Couv_206369.jpg")
                .addPossede("9","Yggdrasil","http://www.bedetheque.com/media/Couvertures/Couv_270707.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/CrepusculeDesDieuxLe0_24072009_052139.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "Gardien du Feu")
                .addPossede( "1", "Goulven", "http://www.bedetheque.com/media/Couvertures/GardienDuFeuLe1_27022009_162821.jpg")
                .addPossede( "2", "Adèle", "http://www.bedetheque.com/media/Couvertures/Couv_108961.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/GardienDuFeuLe1_27022009_162821.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Frere Pardon")
                .addPossede( "1", "Les eaux de Theodeus", "http://www.bedetheque.com/media/Couvertures/frerepardoncouv.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/frerepardoncouv.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "Les forets d'Opale")
                .addPossede( "1", "Le bracelet de Cohars", "http://www.bedetheque.com/media/Couvertures/foretsdopale01.jpg")
                .addPossede( "2", "L'envers du grimoire", "http://www.bedetheque.com/media/Couvertures/Couv_6086.jpg")
                .addPossede( "3", "La cicatrice verte", "http://www.bedetheque.com/media/Couvertures/foretsdopale03couv.jpg")
                .addPossede( "4", "Les Geôles de Nénuphe", "http://www.bedetheque.com/media/Couvertures/foretsdopale04.jpg")
                .addPossede( "5", "Onze racines", "http://www.bedetheque.com/media/Couvertures/Couv_62848.jpg")
                .addPossede( "6", "Le sortilège du pontife", "http://www.bedetheque.com/media/Couvertures/ForetsDOpale06_98350.jpg")
                .addPossede( "7", "Les Dents de pierre", "http://www.bedetheque.com/media/Couvertures/Couv_144393.jpg")
                .addPossede( "8", "Les hordes de la nuit", "http://www.bedetheque.com/media/Couvertures/Couv_199362.jpg")
                .addPossede("9","Un flot de lumière","http://www.bedetheque.com/media/Couvertures/Couv_261106.jpg")
                .addPossede("10","Le Destin du jongleur","https://www.bedetheque.com/media/Couvertures/Couv_315467.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/foretsdopale01.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Siegfried")
                .addPossede( "1", "Siegfried", "http://www.bedetheque.com/media/Couvertures/Couv_67936.jpg")
                .addPossede( "2", "La Walkyrie", "http://www.bedetheque.com/media/Couvertures/Couv_91823.jpg")
                .addPossede( "3", "le crepuscule des dieux", "http://www.bedetheque.com/media/Couvertures/Couv_141483.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_67936.jpg")
                .withEditeur("Dargaud")
                .withFini(true));

        c.addSerie(new Serie( "Arctica")
                .addPossede( "1", "10.000 ans sous les glaces", "http://www.bedetheque.com/media/Couvertures/Couv_69106.jpg")
                .addPossede( "2", "Mystere sous la mer", "http://www.bedetheque.com/media/Couvertures/Couv_77647.jpg")
                .addPossede( "3", "Le passager de la prehistoire", "http://www.bedetheque.com/media/Couvertures/Couv_96643.jpg")
                .addPossede( "4", "Revelations", "http://www.bedetheque.com/media/Couvertures/Couv_117993.jpg")
                .addPossede( "5", "Destination terre", "http://www.bedetheque.com/media/Couvertures/Couv_179601.jpg")
                .addPossede( "6", "Les fugitifs", "http://www.bedetheque.com/media/Couvertures/Couv_203644.jpg")
                .addPossede("7","Le Messager du cosmos","http://www.bedetheque.com/media/Couvertures/Couv_237685.jpg")
                .addPossede("8","Ultimatum","http://www.bedetheque.com/media/Couvertures/Couv_291293.jpg")
                .addPossede("9","Commando noir","https://www.bedetheque.com/media/Couvertures/Couv_312786.jpg")
                .addManquante("10","Le complot","https://www.bedetheque.com/media/Couvertures/Couv_361308.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_69106.jpg")
                .withEditeur("Delcourt")
                .withFini(false));

        c.addSerie(new Serie( "Black Op")
                .addManquante( "1", "Tome 1", "http://www.bedetheque.com/media/Couvertures/blackop01.jpg")
                .addManquante( "2", "Tome 2", "http://www.bedetheque.com/media/Couvertures/BlackOp02.jpg")
                .addManquante( "3", "Tome 3", "http://www.bedetheque.com/media/Couvertures/blackop03.jpg")
                .addManquante( "4", "Tome 4", "http://www.bedetheque.com/media/Couvertures/BlackOp4_10042008_184948.jpg")
                .addManquante( "5", "Tome 5", "http://www.bedetheque.com/media/Couvertures/Nubuc_blackop5couv_85641.jpg")
                .addPossede( "6", "Tome 6", "http://www.bedetheque.com/media/Couvertures/BlackOp-couv_100964.jpg")
                .addManquante( "7", "Tome 7", "http://www.bedetheque.com/media/Couvertures/Couv_201894.jpg")
                .addManquante( "8", "Tome 8", "http://www.bedetheque.com/media/Couvertures/Couv_229164.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/BlackOp-couv_100964.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "La quete de l'oiseau du temps")
                .addManquante( "1", "La conque de Ramor", "http://www.bedetheque.com/media/Couvertures/Couv_15409.jpg")
                .addPossede( "2", "Le temple de l'oubli", "http://www.bedetheque.com/media/Couvertures/Couv_15408.jpg")
                .addManquante( "3", "Le Rige", "http://www.bedetheque.com/media/Couvertures/Couv_321.jpg")
                .addManquante( "4", "L'oeuf des ténébres", "http://www.bedetheque.com/media/Couvertures/Couv_322.jpg")
                .addManquante( "5", "L'ami Javin", "http://www.bedetheque.com/media/Couvertures/Couv_1361.jpg")
                .addManquante( "6", "Le grimoire des dieux", "http://www.bedetheque.com/media/Couvertures/Couv_69122.jpg")
                .addManquante( "7", "La voie du Rige", "http://www.bedetheque.com/media/Couvertures/Couv_105589.jpg")
                .addManquante( "8", "Le chevalier Bragon", "http://www.bedetheque.com/media/Couvertures/Couv_197893.jpg")
                .addManquante("9","L'emprise","https://www.bedetheque.com/media/Couvertures/Couv_311567.jpg")
                .addManquante( "HS1", "Esquisses - L'ami Javin", "http://www.bedetheque.com/media/Couvertures/QueteDeLoiseauDuTempsLaEsquisses_20072006.jpg")
                .addManquante( "HS2", "En quête de l'oiseau du temps", "http://www.bedetheque.com/media/Couvertures/Couv_32442.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_69122.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "Atalantes La légende")
                .addPossede( "1", "Le pacte", "http://www.bedetheque.com/media/Couvertures/Couv_1938.jpg")
                .addPossede( "2", "Nautiliaa", "http://www.bedetheque.com/media/Couvertures/Couv_9792.jpg")
                .addPossede( "3", "Les mystères de Samothrace", "http://www.bedetheque.com/media/Couvertures/atalante03.jpg")
                .addManquante( "4", "L'envol des Boréades", "http://www.bedetheque.com/media/Couvertures/Couv_88913.jpg")
                .addManquante( "5", "Calaïs et Zétès", "http://www.bedetheque.com/media/Couvertures/Couv_177341.jpg")
                .addManquante( "6", "Le labyrinthe d'Hadès ", "http://www.bedetheque.com/media/Couvertures/Couv_199367.jpg")
                .addManquante( "7", "Le Dernier des Grands Anciens", "http://www.bedetheque.com/media/Couvertures/Couv_227224.jpg")
                .addManquante("8","Les Taureaux de Colchide","http://www.bedetheque.com/media/Couvertures/Couv_260179.jpg")
                .addManquante("9","Le Secret d'Héraclès","https://www.bedetheque.com/media/Couvertures/Couv_291412.jpg")
                .addManquante("10","Les Hordes de Sargon","https://www.bedetheque.com/media/Couvertures/Couv_315468.jpg")
                .addManquante( "HS 1", "Les amis d'Atalantes", "http://www.bedetheque.com/media/Couvertures/Couv_30442.jpg")
                .addManquante("11","Retour aux sources","https://www.bedetheque.com/media/Couvertures/Couv_363136.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_1938.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "Les 4 As")
                .addPossede( "", "La Saucisse volante", "")
                .addPossede( "", "Le diamant bleu", "")
                .addPossede( "", "Le magicien", "")
                .addPossede( "", "et la bombe F", "")
                .addPossede( "", "Hold up big bank", "")
                .addPossede( "", "Et le couroucoucou", "")
                .addPossede( "", "Le chateau malefique", "")
                .addPossede( "", "La licorne", "")
                .addPossede( "", "L'atlantide", "")
                .addPossede( "", "La ruee vers l'or", "")
                .addPossede( "", "Le visiteur de minuit", "")
                .addPossede( "", "Le secret de la montagne", "")
                .addPossede( "", "Le serpent de mer", "")
                .addManquante( "", "Les 4 as et l'aeroglisseur", "")
                .addPossede( "", "Les 4 as et la vache sacree", "")
                .addPossede( "", "Les 4 as et la coupe d'or", "")
                .addManquante( "", "Les 4 as et le dragon des neiges", "")
                .addManquante( "", "Les 4 as et le rallye olympique", "")
                .addPossede( "", "Les 4 as et l'île du robinson", "")
                .addPossede( "", "Les 4 as et le tyran", "")
                .addManquante( "", "Les 4 as et le Picasso vole", "")
                .addPossede( "", "Les 4 as et le gang des chapeaux blancs", "")
                .addPossede( "", "Les 4 as et le vaisseau fantôme", "")
                .addManquante( "", "Les 4 as et l'iceberg", "")
                .addManquante( "", "Les 4 as et le tresor des tsars", "")
                .addManquante( "", "Les 4 as et la deesse des mers", "")
                .addManquante( "", "Les 4 as et la navette spatiale", "")
                .addManquante( "", "Les 4 as et le requin geant", "")
                .addManquante( "", "Les 4 as et l'empire cache", "")
                .addManquante( "", "Les 4 as et le mystere de la jungle", "")
                .addManquante( "", "Les 4 as et les extraterrestres", "")
                .addManquante( "", "Les 4 as et le fantôme du Mont Saint-Michel", "")
                .addManquante( "", "Les 4 as et le robot vandale", "")
                .addManquante( "", "Les 4 as et les sorcieres", "")
                .addManquante( "", "Les 4 as et les dinosaures", "")
                .addManquante( "", "Les 4 as et la momie", "")
                .addManquante( "", "Les 4 as et les fantômes", "")
                .addManquante( "", "Les 4 as et le monstre des oceans", "")
                .addManquante( "", "Les 4 As et Halloween", "")
                .addManquante( "", "Le loup de Tasmanie", "")
                .addManquante( "", "Les 4 as et le grand supreme", "")
                .addManquante( "", "Mission Mars", "")
                .addManquante( "", "La balade des 4 as", "")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/quatreas8_03112002.jpg")
                .withEditeur("Casterman")
                .withFini(false));

        c.addSerie(new Serie( "Merlin (Istin/Lambert)")
                .addPossede( "1", "La colère d'Ahès ", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleilcouv01.jpg")
                .addPossede( "2", "L'éveil du pouvoir", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil02.jpg")
                .addPossede( "3", "Le Cromm-Cruach", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil03.jpg")
                .addPossede( "4", "Avalon", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil04.jpg")
                .addPossede( "5", "Brendann le maudit", "http://www.bedetheque.com/media/Couvertures/Merlinsoleil05.jpg")
                .addPossede( "6", "L'ermite et le nid", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil06.jpg")
                .addPossede( "7", "Le chaudron de Bran-le-Béni", "http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil07.jpg")
                .addPossede( "8", "L'aube des armes", "http://www.bedetheque.com/media/Couvertures/merlinsoleil08.jpg")
                .addPossede( "9", "Le secret du codex", "http://www.bedetheque.com/media/Couvertures/MerlinNucleasoleil9_06122007_203254.jpg")
                .addPossede( "10", "La princesse d'Ys", "http://www.bedetheque.com/media/Couvertures/Couv_99942.jpg")
                .addPossede( "11", "Le Roi Arthur", "http://www.bedetheque.com/media/Couvertures/Couv_224196.jpg")
                .addPossede( "12", "La reine de sang", "http://www.bedetheque.com/media/Couvertures/Couv_288651.jpg")
                .addPossede("13","La crosse et le bâton","https://www.bedetheque.com/media/Couvertures/Couv_327182.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/merlinnucleasoleil03.jpg")
                .withEditeur("Soleil")
                .withFini(false));

        c.addSerie(new Serie( "L'epervier")
                .addPossede( "INT", "1+2", "https://www.bedetheque.com/media/Couvertures/Epervier1_2l.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Epervier1_2l.jpg")
                .withEditeur("Dupuis")
                .withFini(true));

        c.addSerie(new Serie( "Dick Herisson")
                .addPossede( "1", "L'ombre du torrero", "http://www.bedetheque.com/media/Couvertures/Couv_39800.jpg")
                .addPossede( "4", "Le vampire de La coste", "http://www.bedetheque.com/media/Couvertures/dickherisson4couv_6592.jpg")
                .addPossede( "5", "La conspiration des poissoniers", "http://www.bedetheque.com/media/Couvertures/Couv_6593.jpg")
                .addManquante( "2", "Les voleurs d'oreilles", "http://www.bedetheque.com/media/Couvertures/Couv_7625.jpg")
                .addManquante( "3", "L'opera maudit", "http://www.bedetheque.com/media/Couvertures/Couv_32998.jpg")
                .addManquante( "6", "Freres de cendres", "http://www.bedetheque.com/media/Couvertures/dickherisson6couv_6594.jpg")
                .addManquante( "7", "Le tombeau d'Absalom", "http://www.bedetheque.com/media/Couvertures/Couv_6595.jpg")
                .addManquante( "8", "La maison du pendu", "http://www.bedetheque.com/media/Couvertures/dickherisson8couv_6596.jpg")
                .addManquante( "9", "Le 7 ieme cri", "http://www.bedetheque.com/media/Couvertures/Couv_6597.jpg")
                .addManquante( "10", "La brouette des morts", "http://www.bedetheque.com/media/Couvertures/Couv_18638.jpg")
                .addManquante( "11", "L'araignee pourpre 1/2", "http://www.bedetheque.com/media/Couvertures/Couv_39543.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/DickHerisson1a_21022005.jpg")
                .withEditeur("Dargaud")
                .withFini(false));

        c.addSerie(new Serie( "Chaos Team")
                .addPossede( "1.1", "", "http://www.bedetheque.com/media/Couvertures/Couv_180438.jpg")
                .addPossede( "1.2", "", "http://www.bedetheque.com/media/Couvertures/Couv_194532.jpg")
                .addPossede( "2.1", "", "http://www.bedetheque.com/media/Couvertures/Couv_213360.jpg")
                .addManquante( "2.2", "", "")
                .addManquante( "HS1", "La vengeance du béret vert", "http://www.bedetheque.com/media/Couvertures/Couv_153180.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_194532.jpg")
                .withEditeur("Akileos")
                .withFini(false));

        c.addSerie(new Serie( "Malefic Time Luis Royo")
                .addPossede( "1", "Apocalypse", "http://www.bedetheque.com/media/Couvertures/Couv_171145.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_171145.jpg")
                .withEditeur("")
                .withFini(false));

        c.addSerie(new Serie( "Asgard")
                .addPossede( "1", "Pied-de-fer", "http://www.bedetheque.com/media/Couvertures/Couv_151330.jpg")
                .addPossede( "2", "Le Serpent-Monde", "http://www.bedetheque.com/media/Couvertures/Couv_178999.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_227204.jpg")
                .withEditeur("Dargaud")
                .withFini(true));

        c.addSerie(new Serie( "Korrigans")
                .addPossede( "1", "Les enfants de la nuit", "")
                .addPossede( "2", "Guerriers des ténèbres", "")
                .addPossede( "3", "Le peuple de Dana", "")
                .addPossede( "4", "Le seigneur du chaos", "")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/150570_c.jpg")
                .withEditeur("Delcourt")
                .withFini(true));

        c.addSerie(new Serie( "Elric (Blondel/Poli/Recht)")
                .addPossede( "1", "Le trone de rubis", "http://www.bedetheque.com/media/Couvertures/Couv_187244.jpg")
                .addPossede( "2", "Stormbringer", "http://www.bedetheque.com/media/Couvertures/Couv_222568.jpg")
                .addPossede( "3", "Le Loup Blanc", "https://www.bedetheque.com/media/Couvertures/Couv_309200.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_187244.jpg")
                .withEditeur("Glenat")
                .withFini(true));

        c.addSerie(new Serie( "Tif et Tondu")
                .addPossede( "5", "En amérique centrale", "")
                .addPossede( "22", "Un plan démoniaque", "")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_215593.jpg")
                .withEditeur("Dupuis")
                .withFini(false));

        c.addSerie(new Serie( "Les druides")
                .addPossede( "1", "Le mystère des Oghams ", "http://www.bedetheque.com/media/Couvertures/DruidesLes1_25102005.jpg")
                .addPossede( "2", "Is la blanche", "http://www.bedetheque.com/media/Couvertures/DruidesLes2_26092006.jpg")
                .addPossede( "3", "La lance de Lug", "http://www.bedetheque.com/media/Couvertures/DruidesLes3_19062007_173616.jpg")
                .addPossede( "4", "La ronde des géants", "http://www.bedetheque.com/media/Couvertures/DruidesLes4_24062008_230934.jpg")
                .addPossede( "5", "La Pierre de destinée", "http://www.bedetheque.com/media/Couvertures/Couv_96819.jpg")
                .addPossede( "6", "Crépuscule", "http://www.bedetheque.com/media/Couvertures/Couv_156671.jpg")
                .addPossede( "7", "Les disparus de Cornouailles ", "http://www.bedetheque.com/media/Couvertures/Couv_172933.jpg")
                .addPossede( "8", "Les Secrets d'Orient", "http://www.bedetheque.com/media/Couvertures/Couv_225471.jpg")
                .addPossede( "9", "Le temps des corbeaux", "http://www.bedetheque.com/media/Couvertures/Couv_288648.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_199535.jpg")
                .withEditeur("Soleil Celtic")
                .withFini(true));

        c.addSerie(new Serie( "La foret")
                .addPossede( "1", "La foret", "https://www.bedetheque.com/media/Couvertures/Couv_62310.jpg")
                .addPossede( "2", "Le logis des ames", "https://www.bedetheque.com/media/Couvertures/Couv_80394.jpg")
                .addManquante( "3", "A vida y a muert", "https://www.bedetheque.com/media/Couvertures/Couv_103242.jpg")
                .addManquante( "4", "La veuve noire", "https://www.bedetheque.com/media/Couvertures/Couv_117138.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_62310.jpg")
                .withEditeur("Casterman")
                .withFini(false));

        c.addSerie(new Serie( "Slhoka")
                .addPossede( "1", "L'île oubliée", "http://www.bedetheque.com/media/Couvertures/Couv_6308.jpg")
                .addPossede( "2", "Les Jardins de Sangalî", "http://www.bedetheque.com/media/Couvertures/slhoka2couv_25655.jpg")
                .addPossede( "3", "Le monde blanc", "http://www.bedetheque.com/media/Couvertures/slhoka3couv_37205.jpg")
                .addPossede( "4", "Les arches de sang", "http://www.bedetheque.com/media/Couvertures/Couv_110896.jpg")
                .addPossede( "5", "L'eveil", "http://www.bedetheque.com/media/Couvertures/Couv_133657.jpg")
                .addPossede( "6", "Les meandres", "http://www.bedetheque.com/media/Couvertures/Couv_170655.jpg")
                .addPossede( "7", "L'Autre rive", "http://www.bedetheque.com/media/Couvertures/Couv_190911.jpg")
                .addPossede( "8", "L'epingle des ephemeres", "http://www.bedetheque.com/media/Couvertures/Couv_218816.jpg")
                .addPossede( "9","Les Deux Roynes","http://www.bedetheque.com/media/Couvertures/Couv_250209.jpg")
                .addPossede( "10","Le dernier guardien","http://www.bedetheque.com/media/Couvertures/Couv_287106.jpg")
                .addPossede( "11","Cellule de crise","https://www.bedetheque.com/media/Couvertures/Couv_309888.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_163697.jpg")
                .withEditeur("Soleil")
                .withFini(true));

        c.addSerie(new Serie( "Blake et Mortimer")
                .addPossede( "1 2 3", "Le secret de l'Espadon", "http://www.bedetheque.com/media/Couvertures/BlakeMortimerInt01a_13102002.jpg")
                .addPossede( "4 5", "Le mystere de la grande pyramide", "http://www.bedetheque.com/media/Couvertures/BlakeEtMortimer34_16112005.jpg")
                .addPossede( "6", "La marque jaune", "http://www.bedetheque.com/media/Couvertures/Couv_7657.jpg")
                .addPossede( "7", "L'enigme de l'Atlantide", "http://www.bedetheque.com/media/Couvertures/BlakeEtMortimerEditionsBlakeEtMortimer7_22062008_201114.jpg")
                .addPossede( "8", "S.O.S. meteores", "http://www.bedetheque.com/media/Couvertures/blakeetmortimer08_edbm.jpg")
                .addPossede( "9", "Le piege diabolique", "http://www.bedetheque.com/media/Couvertures/BlakeetMortimerBM09.jpg")
                .addPossede( "10", "L'affaire du collier", "http://www.bedetheque.com/media/Couvertures/blakeetmortimer10.jpg")
                .addPossede( "11 12", "Les 3 formules du Professeur Sato", "http://www.bedetheque.com/media/Couvertures/Couv_268195.jpg")
                .addPossede( "13", "L'affaire Francis Blake", "http://www.bedetheque.com/media/Couvertures/Couv_7664.jpg")
                .addPossede( "14", "La machination Voronov", "http://www.bedetheque.com/media/Couvertures/Couv_7665.jpg")
                .addPossede( "15", "L'etrange rendez-vous", "http://www.bedetheque.com/media/Couvertures/Couv_7667.jpg")
                .addPossede( "16 17", "Les sarcophages du 6e continent", "http://www.bedetheque.com/media/Couvertures/blakeetmortimer16_edbm.jpg")
                .addPossede( "18", "Le sanctuaire du Gondwana", "http://www.bedetheque.com/media/Couvertures/Couv_73189.jpg")
                .addPossede( "19 20", "La malediction des trente deniers", "http://www.bedetheque.com/media/Couvertures/Couv_96034.jpg")
                .addPossede( "21", "Le serment des cinq lords", "http://www.bedetheque.com/media/Couvertures/Couv_170145.jpg")
                .addPossede( "22", "L'onde Septimus", "http://www.bedetheque.com/media/Couvertures/Couv_197200.jpg")
                .addPossede( "23", "Le baton de Plutarque 12/2014", "http://www.bedetheque.com/media/Couvertures/Couv_226934.jpg")
                .addPossede( "24", "Le Testament de William S.", "http://www.bedetheque.com/media/Couvertures/Couv_293206.jpg")
                .addPossede( "25","La Vallée des Immortels : Menace sur Hong Kong","https://www.bedetheque.com/media/Couvertures/Couv_348626.jpg")
                .addManquante("26","La Vallée des Immortels - Tome 2 - Le Millième Bras du Mékong","https://www.bedetheque.com/media/Couvertures/Couv_377354.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_115948.jpg")
                .withEditeur("Black et Mortimer")
                .withFini(true));


        c.addSerie(new Serie( "Harry Dickson (Vanderhaeghe/Zanon) ")
                .addPossede( "1", "La bande de l'araignee", "https://www.bedetheque.com/media/Couvertures/Couv_24849.jpg")
                .addPossede( "2", "Les spectres bourreaux", "http://www.bedetheque.com/media/Couvertures/Couv_12432.jpg")
                .addPossede( "3", "Les 3 cercles de l'epouvante", "http://www.bedetheque.com/media/Couvertures/Couv_1854.jpg")
                .addPossede( "4", "Le royaume introuvable", "http://www.bedetheque.com/media/Couvertures/Couv_3120.jpg")
                .addPossede( "5", "L'etrange lueur verte", "http://www.bedetheque.com/media/Couvertures/Couv_3121.jpg")
                .addPossede( "6", "La conspiration fantastique", "http://www.bedetheque.com/media/Couvertures/Couv_3122.jpg")
                .addPossede( "7", "Echec au roi", "https://www.bedetheque.com/media/Couvertures/Couv_8620.jpg")
                .addPossede( "8", "Le temple de fer", "https://www.bedetheque.com/media/Couvertures/Couv_39999.jpg")
                .addManquante( "9", "Les gardiens du gouffre 09/2014", "http://www.bedetheque.com/media/Couvertures/Couv_224288.jpg")
                .addManquante("10","Les gardiens du diable 04/2015","http://www.bedetheque.com/media/Couvertures/Couv_244116.jpg")
                .addManquante("11","Le messager des dieux et le vol de l'agneau mystique 16/09/2016","http://www.bedetheque.com/media/Couvertures/Couv_288312.jpg")
                .addManquante("12","La chambre rouge","https://www.bedetheque.com/media/Couvertures/Couv_312214.jpg")
                .addManquante("13"," L'or de Malacca","https://www.bedetheque.com/media/Couvertures/Couv_334030.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_24849.jpg")
                .withEditeur("Art & B.D.")
                .withFini(false));

        c.addSerie(new Serie("Le Codex Angelique")
                .addPossede("1", "Izaël","http://www.bedetheque.com/media/Couvertures/codexangelique01.jpg")
                .addPossede("2", "Lisa","http://www.bedetheque.com/media/Couvertures/Couv_66086.jpg")
                .addPossede("3", "Thomas","http://www.bedetheque.com/media/Couvertures/codexangelique03_83669.jpg")
                .withEditeur("Delcourt")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/codexangelique01.jpg")
        );

        c.addSerie(new Serie("L'épée de cristal")
                .addPossede("1", "Le parfum des Grinches","http://www.bedetheque.com/media/Couvertures/Couv_661.jpg")
                .addPossede("2", "Le regard de Wenlok","http://www.bedetheque.com/media/Couvertures/Couv_662.jpg")
                .addPossede("3", "La main de la Mangrove","http://www.bedetheque.com/media/Couvertures/Couv_663.jpg")
                .addPossede("4", "Le cri du Grouse","http://www.bedetheque.com/media/Couvertures/Couv_664.jpg")
                .addPossede("5", "Le goût de Sulfur","http://www.bedetheque.com/media/Couvertures/Couv_665.jpg")
                .addPossede("6", "La cité des vents","http://www.bedetheque.com/media/Couvertures/Couv_36023.jpg")
                .withEditeur("Vents d'Ouest")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_661.jpg"));

        c.addSerie(new Serie("Gunnm")
                .addPossede("1", "Tome 1","http://www.bedetheque.com/media/Couvertures/Couv_8153.jpg")
                .addPossede("2", "Tome 2","http://www.bedetheque.com/media/Couvertures/Couv_8154.jpg")
                .addPossede("3", "Tome 3","http://www.bedetheque.com/media/Couvertures/Couv_11986.jpg")
                .addPossede("4", "Tome 4","http://www.bedetheque.com/media/Couvertures/Couv_11987.jpg")
                .addPossede("5", "Tome 5","http://www.bedetheque.com/media/Couvertures/Couv_11988.jpg")
                .addPossede("6", "Tome 6","http://www.bedetheque.com/media/Couvertures/Couv_21787.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_8153.jpg")
                .withEditeur("Glénat"));

        c.addSerie(new Serie("Dangoo")
                .addPossede("1", "Tome 1","http://www.bedetheque.com/media/Couvertures/Couv_120767.jpg")
                .addPossede("2", "Tome 2","http://www.bedetheque.com/media/Couvertures/Couv_101696.jpg")
                .addPossede("3", "Tome 3","http://www.bedetheque.com/media/Couvertures/DANGOO_03_101697.jpg")
                .addPossede("4", "Tome 4","http://www.bedetheque.com/media/Couvertures/DANGOO_04_101698.jpg")
                .addPossede("5", "Tome 5","http://www.bedetheque.com/media/Couvertures/Dangoo5_21112006.jpg")
                .addManquante("6", "Tome 6","http://www.bedetheque.com/media/Couvertures/Couv_123893.jpg")
                .addManquante("7", "Tome 7","http://www.bedetheque.com/media/Couvertures/Couv_123895.jpg")
                .addManquante("8", "Tome 8","http://www.bedetheque.com/media/Couvertures/Couv_123896.jpg")
                .addManquante("9", "Tome 9","http://www.bedetheque.com/media/Couvertures/Couv_123897.jpg")
                .withImageUrl("http://www.bedetheque.com/media/Couvertures/Couv_120767.jpg")
                .withEditeur("Samji"));

        c.addSerie(new Serie("Kwaïdan")
                .addPossede("1", "L'esprit du lac","https://www.bedetheque.com/media/Couvertures/Couv_2179.jpg")
                .addManquante("2", "Setsuko","http://www.bedetheque.com/media/Couvertures/kwaidan02.jpg")
                .addPossede("3", "Métamorphose","https://www.bedetheque.com/media/Couvertures/Couv_26890.jpg")

                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_2179.jpg")
                .withEditeur("Delcourt"));

        c.addSerie(new Serie("La graine de Folie")
                .addPossede("1", "Igguk","https://www.bedetheque.com/media/Couvertures/Couv_890.jpg")
                .addPossede("2", "Le grand ornement","https://www.bedetheque.com/media/Couvertures/kwaidan02.jpg")
                .addPossede("3", "La Morrydwen","https://www.bedetheque.com/media/Couvertures/Couv_1751.jpg")
                .addPossede("4", "Le roy sans cœur","https://www.bedetheque.com/media/Couvertures/Couv_19701.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_890.jpg")
                .withEditeur("Delcourt"));

        c.addSerie(new Serie("La cathédrale des Abymes")
                .addPossede("1","L'Évangile d'Ariathie","https://www.bedetheque.com/media/Couvertures/Couv_341999.jpg")
                .addManquante("2","La guilde des assassins","https://www.bedetheque.com/media/Couvertures/Couv_353816.jpg")
                .addManquante("3","Quand vient le sage...","https://www.bedetheque.com/media/Couvertures/Couv_375017.jpg")
                .withImageUrl("https://www.bedetheque.com/media/Couvertures/Couv_341999.jpg")
                .withEditeur("Soleil Productions"));
        return c;
    }


    public static Long next(boolean withId) {
        if (withId) {
            return i++;
        } else {
            return null;
        }
    }
}
